export const getPayload = (width: number, height: number, image_id: string, file_id: string, x: number, y: number, url: string = "http://oswinjerome.in") => {
  const payload = {
    x: x,
    y: y,
    id: image_id,
    link: url,
    seed: 1206674827,
    type: "image",
    angle: 0,
    index: "abl",
    scale: [1, 1],
    width: width,
    fileId: file_id,
    height: height,
    locked: false,
    status: "pending",
    frameId: null,
    opacity: 100,
    updated: 1744137259095,
    version: 743,
    groupIds: [],
    fillStyle: "solid",
    isDeleted: false,
    roughness: 1,
    roundness: null,
    strokeColor: "transparent",
    strokeStyle: "solid",
    strokeWidth: 2,
    versionNonce: 1468768930,
    boundElements: [],
    backgroundColor: "transparent",
  };
  return payload;
};
